name: experimental
description: An experimental web GUI for Syncthing

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  json_serializable: ^2.0.0

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
